server:
  port: 8080

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lesson-23
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false